### ISSUE TITLE
Support card carousel

### ISSUE THREAD

**Issue by aegaas** [zendesk/sunshine-conversations-web#552]
Hello,

I'm trying to build a bot in motion.ai and using smooch's clearly superior web UI. Unfortunately when responding with the bot with a card carousel, I see no content in smooch. I'm not married to motion.ai's as the backend for the bot, but our client really likes chat cards. What are our options?

In Motion.ai:
![pasted image at 2017_06_23 01_13 pm](https://user-images.githubusercontent.com/455027/27498870-e9f480cc-5815-11e7-8235-7fe10520b8ca.png)

In Smooch UI:
![smooch web chat](https://user-images.githubusercontent.com/455027/27498831-b9ba308c-5815-11e7-8e2e-a17be0cd6d20.png)

**Comment by aegaas** [comment]
I figured out the issue was that the description that was written was too long for smooch to support. I shortened the desciption, but it just shows up as text, not even with inline pictures! Card support would still be killer here.

**Comment by lemieux** [comment]
Hey @aegaas,

carousel support is on our roadmap for the Web Messenger, but I don't have an ETA for it unfortunately. I'll pass the request to our product team to make sure they know that people are asking for it.

**Comment by jflebeau** [comment]
Having a carousel as powerful as the one on Messenger (i.e. with buttons tied to each card) would make all the difference.

**Comment by brunoalano** [comment]
A made a simple implementation for now (its really simple):

```javascript
import React, { Component } from 'react';
import { Carousel } from 'react-responsive-carousel';
import { SEND_STATUS } from '../constants/message';
import { Action } from './action';

export class CarouselCard extends Component {
  static propTypes = {
    title: React.PropTypes.string,
    description: React.PropTypes.string,
    mediaUrl: React.PropTypes.string,
    mediaType: React.PropTypes.string,
    size: React.PropTypes.string,
    actions: React.PropTypes.array,
  }

  render() {

    // List of Actions
    const actionList = this.props.actions.map((action) => {
        return (
          <li key={ action._id }>
            <Action key={ action._id } {...action} />
          </li>
        );
    });

    return (
      <div className="card">
        <a href="#">
          <div className="card-image">
            <img src={this.props.mediaUrl} />
          </div>

          <h4>{this.props.title}</h4>
          <div className="card-description">
            {this.props.description}
          </div>
        </a>

        <ul className="card-actions">
          { actionList }
        </ul>
      </div>
    );
  }
}

export class CarouselMessage extends Component {
    static propTypes = {
      items: React.PropTypes.array.isRequired,
      type: React.PropTypes.string,
      role: React.PropTypes.string.isRequired
    };

    state = {};

    render() {
      // Slider Settings
      var settings = {
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 1,
        slidesToScroll: 1
      };

      // Prepare each card that will be available on the slider
      const cardsList = this.props.items.map((item, idx) => {
        return (
          <div key={idx}>
            <CarouselCard {...item} />
          </div>
        );
      });

      // Render
      return (
        <div className="carouselContainer">
          <Carousel showThumbs={false} showArrows={true} showStatus={false} showIndicators={false}>
            { cardsList }
          </Carousel>
        </div>
      );
    }
}
```

**Comment by aegaas** [comment]
Thanks @brunoalano we'll try this out and await an official solution!

**Comment by PhanTien** [comment]
Hi all, Im a new programmer, I'm developing a chatbot by api.ai + smooch.io and im using smooch's web UI .I found this issue and saw that it's helpful for me but i have zero knowledge about react js so please tell me how can i add this simple implementation to my chatbot.I've already have source code and customize some action's UI by myself, but i dont know how to add new actions and how they work. Many thanks and sorry for my bad english.

**Comment by jflebeau** [comment]
Still no ETA on carousel support?

**Comment by Carson12345** [comment]
@brunoalano 

Thanks so much for your advice here:

May I know after you include the component you wrote, where did you put it into in order the make the cards show properly in the message please? Did you add some specific css properties to make it work please?

I have put it at the original **message.jsx** file of smooch this way, but it doesn't show properly, I am wondering if I have implement it wrong? It would be my pleasure if I can have your advice again!

<img width="300" alt="screen shot 2017-09-30 at 1 39 37 am" src="https://user-images.githubusercontent.com/22004238/31028378-4250531a-a580-11e7-991d-eb8aa9444191.png">


`
        return <div className={ rowClass.join(' ') }>
                   { !isAppUser && firstInGroup ? fromName : null }
                   { lastInGroup ? avatar : avatarPlaceHolder }
                   <div className='sk-msg-wrapper'>
                       <div className={ containerClasses.join(' ') }
                            style={ style }
                            ref='messageContent'
                            onClick={ this.onMessageClick.bind(this) }>
                           { imagePart ? imagePart : null }
                           { textPart ? textPart : null }
                           { locationPart ? locationPart : null }
                           { hasActions ? <div className={ actionListClasses.join(' ') }>
                                              { actionList }
                                          </div> : null }
                                          
                           { hasItems ? <div className={ cardListClasses.join(' ') }>
                                                <Carousel {...this.props}/>
                                          </div>: null }
                                         
                       </div>
                       { sendStatus === SEND_STATUS.FAILED ? clickToRetry : null }
                   </div>
                   <div className='sk-clear'></div>
               </div>;`

Before this I was using the React-Slick by Akiran (https://github.com/akiran/react-slick), it works except that when I refresh the page, the cards all reinitialize with width 0...

**Comment by brunoalano** [comment]
Sorry, I'm not working more with Smooch. But here is the stylesheet that I've created to make it work (put in `conversation.less`)

```less
.carouselContainer {
  padding: 10px;
  margin: 0 auto;

  .card {
    background-color: #fafafa !important;
    margin: 0px 4px;
    font-size: 16px!important;
    min-height: 20px;
    border: 1px solid #e4eaec;
    border-radius: 3px;
    width: 100%;
    height: 100%;

    .card-img-top-250 { max-height: 250px; overflow: hidden; }
    .card-img-top {
      border-top-right-radius: .25rem;
      border-top-left-radius: .25rem;
      border-bottom: 1px solid #e4eaec;
      .img-fluid {
        display: block;
        max-width: 100%;
        height: auto;
        vertical-align: middle;
      }
    }

    .p-t-2 { padding-top: 1rem!important; }
    .p-b-2 { padding-bottom: 1.5rem!important; }
    .card-block {
      padding: 1.25rem;

      h6 {
        color: rgba(0, 0, 0, .40);
        line-height: 1.28em;
        font-size: 16px;
        font-weight: 400;
        padding: 0 10px;
        margin-top: 4px;
      }

      h2 {
        margin-top: 0px;
        overflow-y: auto;
        font-size: 16px!important;
        color: #3b3b3b;
        text-shadow: rgba(0,0,0,.15) 0 0 1px;
        font-weight: 700;
        line-height: 1.2;
        padding: 0 10px;
      }
    }

    ul.card-actions {
      list-style: none;
      border-top: 1px solid #e4eaec;
      margin-top: 4px;
      padding-bottom: 4px;
      padding-top: 4px;
      li {
        width: 100%;
        clear: both;
        text-align: center;
        padding-top: 4px;
        padding-bottom: 4px;
        

        border-top: 1px solid #e4eaec;
        &:first-child { border-top: none; }

        .sk-action {
          a {
            display: block;
            border-radius: 0;
            margin: 0;
            color: #0084ff;
            font-weight: 500;
            padding: 0 10px;
            background: transparent;
            border: 0;

            .sk-fading-circle {
              left: 49%;
              .sk-inner-circle {
                background-color: #787f8c;
              }
            }
          }
        }
      }
    }
  }
}
```

And here my `message.jsx`:

```javascript
import isMobile from 'ismobilejs';
import { connect } from 'react-redux';
import React, { Component, PropTypes } from 'react';

import { TextMessage } from './text-message';
import { ImageMessage } from './image-message';
import { CarouselMessage } from './carousel-message';
import { Action } from './action';
import { findDOMNode } from 'react-dom';
import { getElementProperties } from '../utils/dom';
import { resendMessage } from '../services/conversation';
import { SEND_STATUS, GLOBAL_ACTION_TYPES } from '../constants/message';
import { LoadingComponent } from './loading';

class Message extends Component {
    static propTypes = {
        name: PropTypes.string,
        actions: PropTypes.array,
        type: PropTypes.string.isRequired,
        role: PropTypes.string.isRequired,
        mediaUrl: PropTypes.string,
        text: PropTypes.string,
        accentColor: PropTypes.string,
        linkColor: PropTypes.string,
        firstInGroup: PropTypes.bool,
        lastInGroup: PropTypes.bool,
        sendStatus: PropTypes.string,
        tapToRetryText: PropTypes.string.isRequired,
        clickToRetryText: PropTypes.string.isRequired,
        locationSendingFailedText: PropTypes.string.isRequired
    };

    static defaultProps = {
        actions: [],
        sendStatus: SEND_STATUS.SENT
    };

    componentDidMount() {
        if (this.props.actions.length === 0) {
            this._restyleBubble();
        }
    }

    _restyleBubble() {
        const bubble = findDOMNode(this.refs.messageContent);
        if (bubble) {
            const messageElement = bubble.firstChild;
            const messageProperties = getElementProperties(messageElement);
            const bubbleProperties = getElementProperties(bubble);
            const multiLineCheck = parseInt(bubbleProperties.fontSize) * 2;
            if (messageProperties.height > multiLineCheck && messageProperties.width < bubbleProperties.width) {
                bubble.style.width = (messageProperties.width + parseInt(bubbleProperties.paddingLeft) + parseInt(bubbleProperties.paddingRight)) + 'px';
            }
        }
    }

    onMessageClick() {
        const {sendStatus} = this.props;

        if (sendStatus === SEND_STATUS.FAILED) {
            this.props.dispatch(resendMessage(this.props._clientId));
        }
    }

    render() {
        const {name, role, avatarUrl, text, accentColor, firstInGroup, lastInGroup, linkColor, type, mediaUrl, sendStatus, clickToRetryText, tapToRetryText, locationSendingFailedText} = this.props;
        const actions = this.props.actions.filter(({type}) => !GLOBAL_ACTION_TYPES.includes(type));
        const hasText = text && text.trim() && text.trim() !== mediaUrl;
        const hasFile = type === 'file';
        const hasImage = type === 'image';
        const hasLocation = type === 'location';
        const hasCarousel = type == 'carousel';
        const isAppUser = role === 'appUser';
        const hasActions = actions.length > 0;
        
        let lastItem;
        
        if (hasActions) {
            lastItem = 'actions';        
        } else if (hasText || hasFile) {
            lastItem = 'text';
        } else if (hasLocation) {
            lastItem = 'location'
        }

        const avatarClass = hasImage ? ['sk-msg-avatar', 'sk-msg-avatar-img'] : ['sk-msg-avatar'];
        const avatarPlaceHolder = isAppUser ? null : (<div className='sk-msg-avatar-placeholder' />);
        const containerClasses = ['sk-msg'];

        if (hasImage || actions.length > 0) {
            containerClasses.push('sk-msg-image');
        }

        const actionList = actions.map((action) => {
            return <Action key={ action._id }
                           buttonColor={ linkColor }
                           {...action} />;
        });

        const avatar = isAppUser ? null :
            <img alt={ `${name}'s avatar` }
                 className={ avatarClass.join(' ') }
                 src={ avatarUrl } />;

        const textClasses = ['sk-message-item', 'sk-message-text'];

        if (lastItem === 'text') {
            textClasses.push('sk-last-item');
        }

        const textPart = ((hasText || hasFile)) && <TextMessage {...this.props}
                                                              className={ textClasses.join(' ') } />;
        const imagePart = hasImage && <ImageMessage {...this.props} />;
        const carouselPart = hasCarousel && <CarouselMessage {...this.props} />;

        const style = {};

        if (!hasImage || hasActions || hasText) {
            if (isAppUser && accentColor) {
                style.backgroundColor = style.borderLeftColor = `#${accentColor}`;
            }
        }

        const rowClass = ['sk-row'];

        if (isAppUser) {
            rowClass.push('sk-right-row');
        } else {
            rowClass.push('sk-left-row');
        }

        if (firstInGroup) {
            if (isAppUser) {
                rowClass.push('sk-row-appuser-first');
            } else {
                rowClass.push('sk-row-appmaker-first');
            }
        }

        if (lastInGroup) {
            if (isAppUser) {
                rowClass.push('sk-row-appuser-last');
            } else {
                rowClass.push('sk-row-appmaker-last');
            }
        }

        if (!firstInGroup && !lastInGroup) {
            if (isAppUser) {
                rowClass.push('sk-row-appuser-middle');
            } else {
                rowClass.push('sk-row-appmaker-middle');
            }
        }

        const fromName = <div className='sk-from'>
                             { isAppUser ? '' : name }
                         </div>;

        const actionListClasses = ['sk-message-item'];

        if (lastItem === 'actions') {
            actionListClasses.push('sk-last-item');
        }

        if ([SEND_STATUS.SENDING, SEND_STATUS.FAILED].includes(sendStatus)) {
            containerClasses.push('sk-msg-unsent');
        }

        const clickToRetry = <div className='sk-retry'>
                                 { isMobile.any ? tapToRetryText : clickToRetryText }
                             </div>;


        const locationClasses = ['sk-message-item'];

        if (lastItem === 'location') {
            locationClasses.push('sk-last-item');
        }

        if (sendStatus === SEND_STATUS.SENDING) {
            locationClasses.push('sk-message-location-loading');
        } else {
            locationClasses.push('sk-message-text');
        }

        let locationPart;

        if (type === 'location' && !textPart) {
            locationPart = sendStatus === SEND_STATUS.FAILED ?
                <TextMessage className={ locationClasses.join(' ') }
                             text={ locationSendingFailedText }
                             role={ role } />
                : <div className={ locationClasses.join(' ') }>
                      <LoadingComponent color={ !isAppUser ? accentColor : null } />
                  </div> ;
        }

        return <div className={ rowClass.join(' ') }>
                   { !isAppUser && firstInGroup && !hasCarousel ? fromName : null }
                   { lastInGroup && !hasCarousel ? avatar : avatarPlaceHolder }

                   <div className={'sk-msg-wrapper sk-msg-' + type}>
                       <div className={ containerClasses.join(' ') }
                            style={ style }
                            ref='messageContent'
                            onClick={ this.onMessageClick.bind(this) }>
                            { hasCarousel ? carouselPart : null }
                           { imagePart ? imagePart : null }
                           { textPart && !hasCarousel ? textPart : null }
                           { locationPart ? locationPart : null }
                           { hasActions ? <div className={ actionListClasses.join(' ') }>
                                              { actionList }
                                          </div> : null }
                       </div>
                       { sendStatus === SEND_STATUS.FAILED ? clickToRetry : null }
                   </div>
                   <div className='sk-clear'></div>
               </div>;
    }
}

export const MessageComponent = connect(({ui: {text}}) => {
    return {
        clickToRetryText: text.clickToRetry,
        tapToRetryText: text.tapToRetry,
        locationSendingFailedText: text.locationSendingFailed
    };
})(Message);
```
