### ISSUE TITLE
embedded mode should not have positioning properties

### ISSUE THREAD

**Issue by whollacsek** [zendesk/sunshine-conversations-web#652]
**What is the current behavior?**
When `embedded` is true the injected iframe has these properties which **prevent** proper custom styling:
```css
.displayTab .iframe, .widgetClosed.displayTab .iframe {
    right: 14px;
    bottom: 20px;
    margin-bottom: -1px;
}
```

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem** via
https://plnkr.co, https://codepen.io/, or similar (e.g. a GitHub repository).

set `embedded` to true

 **What is the expected behavior?**

Those properties should not be present.

 **Please tell us about your environment:**
- Delivery method: npm
- Version: 4.3.1
- Browser: all
- OS: Windows, OS X

 **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. Stack Overflow, etc)

Maybe the properties should be reset like follow:
```css
.widgetEmbedded .iframe {
    position: relative;
    height: 100%;
    width: 100%;
    max-height: 100%;
    right: 0;
    bottom: 0;
    margin-bottom: 0;
}
```
